language: csharp
mono: none
dotnet: 3.1.201

before_install:
- sudo apt-get update
- sudo apt-get install -y --allow-unauthenticated libc6-dev libgdiplus libx11-dev
- sudo rm -rf /var/lib/apt/lists/*

install:
- dotnet restore test/SharpOtto.Tests/SharpOtto.Tests.csproj

script:
- dotnet build test/SharpOtto.Tests/SharpOtto.Tests.csproj
- dotnet test test/SharpOtto.Tests/SharpOtto.Tests.csproj