language: csharp
mono: none
dotnet: 3.1.201

install:
- dotnet restore test/SharpOtto.Tests/SharpOtto.Tests.csproj

script:
- dotnet build test/SharpOtto.Tests/SharpOtto.Tests.csproj
- dotnet test test/SharpOtto.Tests/SharpOtto.Tests.csproj